#server:
#  error:
#    include-message: always
#    include-binding-errors: always
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/multiplication;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      fail_on_empty_beans: false