# Includes validation messages in responses
server:
  error:
    include-message: always
    include-binding-errors: always
# Gives us access to the H2 database web console
spring:
  h2:
    console:
      enabled: true
# Creates the database in a file
  datasource:
    url: jdbc:h2:file:~/multiplication;DB_CLOSE_ON_EXIT=FALSE
# Creates or updates the schema if needed
  jpa:
    hibernate:
      ddl-auto: update
# For educational purposes we will show the SQL in console
    show-sql: true

# Gamification service URL
service:
  gamification:
    host: http://localhost:8081
